/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GajiKaryawan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kahfi
 */
public class GajiKaryawan extends javax.swing.JFrame {
    DefaultTableModel tabmode;
    int id, jamKerja, jamLembur, gajiBersih, idJabatan, totalGaji; 
    String nama, jabatan; 

    /**
     * Creates new form GajiKaryawan
     */
    public GajiKaryawan() {
        initComponents();
      
        tampil(); 
    }
    
      public void tampil(){
      DefaultTableModel tbl = new DefaultTableModel(); 
      tbl.addColumn("ID Karyawan");
      tbl.addColumn("Nama");
      tbl.addColumn("Jabatan");
      tbl.addColumn("Jam Kerja");
      tbl.addColumn("Jam lembur");
      tbl.addColumn("Gaji Bersih");
      
      
      try {
          Connection c = koneksi.getKoneksi(); 
          Statement s = c.createStatement(); 
          String sql = "select * from gajipegawai"; 
          ResultSet r = s.executeQuery(sql);  
          while(r.next()){
              tbl.addRow(new Object[]{
                  r.getString("id"),
                  r.getString("nama"), 
                  r.getString("jabatan"), 
                  r.getString("jam_kerja"), 
                  r.getString("jam_lembur"), 
                  r.getString("gaji")
                 
                
                  
              });
             tablePegawai.setModel(tbl);
            
          }
      } catch (Exception e) {
      }
      
  }
    
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldId = new javax.swing.JTextField();
        fieldNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboJabatan = new javax.swing.JComboBox<>();
        fieldJamKerja = new javax.swing.JTextField();
        fieldJamLembur = new javax.swing.JTextField();
        fieldGajibersih = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePegawai = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Program Gaji Karyawan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID Karyawan : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nama Karyawan : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Jabatan : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jam Lembur : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Gaji Bersih : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Jam Kerja : ");

        comboJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Jabatan -", "Direktur Utama", "Manager", "Administasi Gudang", "Satpam" }));

        fieldGajibersih.setEditable(false);
        fieldGajibersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldGajibersihActionPerformed(evt);
            }
        });

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tablePegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePegawai);

        jButton6.setText("Hitung");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldId)
                            .addComponent(fieldNama, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(comboJabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldJamKerja)
                            .addComponent(fieldJamLembur)
                            .addComponent(fieldGajibersih)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(355, 355, 355))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fieldJamKerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fieldJamLembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fieldGajibersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton1)
                            .addComponent(jButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldGajibersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldGajibersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldGajibersihActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       id = Integer.valueOf(fieldId.getText()); 
       nama = fieldNama.getText(); 
       jabatan = (String) comboJabatan.getSelectedItem(); 
       idJabatan = comboJabatan.getSelectedIndex(); 
       jamKerja = Integer.valueOf(fieldJamKerja.getText()); 
       jamLembur = Integer.valueOf(fieldJamLembur.getText()); 
       
       if(idJabatan ==0){
           gajiBersih = (jamKerja * 50000) + (jamLembur * 40000) + (200000); 
       }
       else if(idJabatan==1){
           gajiBersih = (jamKerja * 40000) + (jamLembur * 30000) + (150000); 
       }else if(idJabatan==2){
           gajiBersih = (jamKerja * 30000) + (jamLembur * 20000) + (100000); 
           
       }else if(idJabatan==3){
             gajiBersih = (jamKerja * 20000) + (jamLembur * 10000) + (50000); 
       }else {
           gajiBersih = 0; 
       }
       
       fieldGajibersih.setText(String.valueOf("Rp. " + gajiBersih)); 
      
      
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        try {
                
             id = Integer.valueOf(fieldId.getText()); 
             nama = fieldNama.getText(); 
             jabatan = (String) comboJabatan.getSelectedItem(); 
             jamKerja = Integer.valueOf(fieldJamKerja.getText()); 
             jamLembur = Integer.valueOf(fieldJamLembur.getText()); 
             totalGaji = Integer.valueOf(gajiBersih); 
             String totalGajih = String.valueOf("Rp." + totalGaji); 
             
            
          
            
            Connection c = koneksi.getKoneksi(); 
            Statement s = c.createStatement(); 
            String sql = "insert into gajipegawai values('" + id
                    + "','" + nama
                    + "','" + jabatan + "','" + jamKerja + "','" +  jamLembur + "','" + totalGajih +"')"; 
            s.execute(sql); 
            tampil(); 
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insert Data Gagal");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
         try {
            jabatan = (String) comboJabatan.getSelectedItem(); 
            
            String sql = "update gajipegawai set id='" + fieldId.getText()+
                    "', nama = '" + fieldNama.getText()+
                    "', jabatan = '" + jabatan+
                    "', jam_kerja = '" + fieldJamKerja.getText()+
                    "', jam_lembur = '" + fieldJamLembur.getText()+
                    "', gaji = '" + fieldGajibersih.getText()+
                    "'  where id ='" + fieldId.getText()+"'";
            java.sql.Connection conn = (java.sql.Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql); 
            pst.execute(); 
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tampil();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablePegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePegawaiMouseClicked
       int row = tablePegawai.getSelectedRow(); 
       if(row==row){
           fieldId.setEnabled(false);
           
       }else{
           fieldId.setEnabled(true);
       }
       String tabel_klik = (tablePegawai.getModel().getValueAt(row, 0).toString()); 
        try {
       java.sql.Connection conn = (java.sql.Connection)koneksi.getKoneksi(); 
       java.sql.Statement stm = conn.createStatement(); 
       java.sql.ResultSet sql = stm.executeQuery
        ("select * from gajipegawai where id = '"+tabel_klik + "'");
       if(sql.next()){
           String add1 = sql.getString("id"); 
           fieldId.setText(add1);
           
           
           String add2 = sql.getString("nama"); 
           fieldNama.setText(add2);
           
           String add3 = sql.getString("jabatan"); 
           comboJabatan.setSelectedItem(add3);
           
           String add4 = sql.getString("jam_kerja"); 
           fieldJamKerja.setText(add4);
           
           String add5 = sql.getString("jam_lembur"); 
           fieldJamLembur.setText(add5);
           
           String add6 = sql.getString("gaji"); 
           fieldGajibersih.setText(add6);
           
        
           
       
       }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tablePegawaiMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        fieldId.setText(""); 
        fieldNama.setText(""); 
        fieldJamKerja.setText("");
        fieldJamLembur.setText(""); 
        fieldGajibersih.setText(""); 
        comboJabatan.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
   
        try {
            String id = fieldId.getText(); 
            String sql = "delete from gajipegawai"
                    + " where id = '" + id + "'"; 
            
            java.sql.Connection conn = (java.sql.Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql); 
            pst.execute(); 
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus", "Baca Dulu", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
        tampil();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GajiKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboJabatan;
    private javax.swing.JTextField fieldGajibersih;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldJamKerja;
    private javax.swing.JTextField fieldJamLembur;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePegawai;
    // End of variables declaration//GEN-END:variables
}
